/**
 * Base de connaissances d'exemples RAG pour intentions locales
 * 500 exemples spécifiques au contexte ivoirien et élevage porcin
 * 
 * Ces exemples couvrent :
 * - Expressions locales ivoiriennes
 * - Vocabulaire spécifique à l'élevage porcin
 * - Variations linguistiques (français parlé, français écrit)
 * - Contextes culturels et pratiques locales
 */

import { TrainingExample } from './IntentRAG';
import { AgentActionType } from '../../../types/chatAgent';

/**
 * 500 exemples RAG pour intentions locales (ivoirien, élevage porcin)
 */
export const INTENT_KNOWLEDGE_BASE_LOCAL: TrainingExample[] = [
  // ========== STATISTIQUES (get_statistics) - 50 exemples ==========
  { text: 'combien de cochon j ai', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'nombre de cochons', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mon effectif', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'effectif total', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'combien de tete j ai', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'nombre de tetes', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mon cheptel actuel', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'situation de mon elevage', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'etat de mon cheptel', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'bilan de mon elevage', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'resume de mon elevage', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'combien de porc en vie', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'porcs vivants', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mes animaux actifs', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'total de mes porcs', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mon nombre de porc', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'combien j ai de tete', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mon effectif porcin', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'taille de mon cheptel', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'nombre total de porcs', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'combien de porc j eleve', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mes porcs', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'mon elevage', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'mon cheptel', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'mes betes', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'mes animaux', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'stat', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'stats', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'bilan', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'resume', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'situation', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'etat', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'combien', action: 'get_statistics', params: {}, confidence: 0.8 },
  { text: 'nombre', action: 'get_statistics', params: {}, confidence: 0.8 },
  { text: 'effectif', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'cheptel', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'elevage', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'porcs', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'cochons', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'tetes', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'betes', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'animaux', action: 'get_statistics', params: {}, confidence: 0.85 },
  { text: 'mon effectif actuel', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'combien de porc en ce moment', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'nombre actuel de porcs', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'mon cheptel aujourd hui', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'situation actuelle', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'etat actuel', action: 'get_statistics', params: {}, confidence: 0.9 },
  { text: 'bilan actuel', action: 'get_statistics', params: {}, confidence: 0.95 },
  { text: 'resume actuel', action: 'get_statistics', params: {}, confidence: 0.9 },

  // ========== VENTES (create_revenu) - 80 exemples ==========
  { text: 'j ai vendu [QUANTITE] porcs a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] porcs a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] cochons a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] cochons a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] tetes a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] tetes a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] betes a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] betes a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] porcs pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] porcs pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] porcs chez [NOM]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vente de [QUANTITE] porcs a [NOM]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'j ai vendu [QUANTITE] porcs a [NOM] pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vente de [QUANTITE] porcs a [NOM] pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'j ai vendu [QUANTITE] porcs a [MONTANT] fcfa', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] porcs a [MONTANT] francs', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] porcs a [MONTANT] f', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [QUANTITE] porcs a [MONTANT] f cfa', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [QUANTITE] porcs aujourd hui', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vente de [QUANTITE] porcs aujourd hui', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vendu [QUANTITE] porcs ce matin', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vente de [QUANTITE] porcs ce matin', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vendu [QUANTITE] porcs hier', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vente de [QUANTITE] porcs hier', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vendu [QUANTITE] porcs la semaine passee', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vente de [QUANTITE] porcs la semaine passee', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vendu [QUANTITE] porcs le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'vente de [QUANTITE] porcs le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'j ai vendu [QUANTITE] porcs a [MONTANT] le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'vente de [QUANTITE] porcs a [MONTANT] le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'j ai vendu [QUANTITE] porcs a [NOM] le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', date: '[DATE]' }, confidence: 0.97 },
  { text: 'vente de [QUANTITE] porcs a [NOM] le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', date: '[DATE]' }, confidence: 0.97 },
  { text: 'j ai vendu [QUANTITE] porcs a [NOM] pour [MONTANT] le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'vente de [QUANTITE] porcs a [NOM] pour [MONTANT] le [DATE]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'j ai vendu un porc a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente d un porc a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu un cochon a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente d un cochon a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu une tete a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente d une tete a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu une bete a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente d une bete a [MONTANT]', action: 'create_revenu', params: { nombre: 1, montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [CODE_ANIMAL] a [MONTANT]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vente de [CODE_ANIMAL] a [MONTANT]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai vendu [CODE_ANIMAL] a [NOM]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vente de [CODE_ANIMAL] a [NOM]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'j ai vendu [CODE_ANIMAL] a [NOM] pour [MONTANT]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vente de [CODE_ANIMAL] a [NOM] pour [MONTANT]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'j ai vendu [CODE_ANIMAL] a [MONTANT] le [DATE]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'vente de [CODE_ANIMAL] a [MONTANT] le [DATE]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'j ai vendu [CODE_ANIMAL] a [NOM] le [DATE]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', date: '[DATE]' }, confidence: 0.97 },
  { text: 'vente de [CODE_ANIMAL] a [NOM] le [DATE]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', date: '[DATE]' }, confidence: 0.97 },
  { text: 'j ai vendu [CODE_ANIMAL] a [NOM] pour [MONTANT] le [DATE]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'vente de [CODE_ANIMAL] a [NOM] pour [MONTANT] le [DATE]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'vendu [QUANTITE] porcs', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vendu [QUANTITE] cochons', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vendu [QUANTITE] tetes', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vendu [QUANTITE] betes', action: 'create_revenu', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vendu [QUANTITE] porcs a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vendu [QUANTITE] cochons a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vendu [QUANTITE] tetes a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vendu [QUANTITE] betes a [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vendu [QUANTITE] porcs a [NOM]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vendu [QUANTITE] cochons a [NOM]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vendu [QUANTITE] tetes a [NOM]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vendu [QUANTITE] betes a [NOM]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vendu [QUANTITE] porcs a [NOM] pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vendu [QUANTITE] cochons a [NOM] pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vendu [QUANTITE] tetes a [NOM] pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vendu [QUANTITE] betes a [NOM] pour [MONTANT]', action: 'create_revenu', params: { nombre: '[QUANTITE]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vendu [CODE_ANIMAL]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.95 },
  { text: 'vendu [CODE_ANIMAL] a [MONTANT]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'vendu [CODE_ANIMAL] a [NOM]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]' }, confidence: 0.97 },
  { text: 'vendu [CODE_ANIMAL] a [NOM] pour [MONTANT]', action: 'create_revenu', params: { animal_code: '[CODE_ANIMAL]', acheteur: '[NOM]', montant: '[MONTANT]' }, confidence: 0.99 },
  { text: 'vente', action: 'create_revenu', params: {}, confidence: 0.85 },
  { text: 'vendu', action: 'create_revenu', params: {}, confidence: 0.85 },
  { text: 'j ai vendu', action: 'create_revenu', params: {}, confidence: 0.85 },
  { text: 'vente de porc', action: 'create_revenu', params: {}, confidence: 0.9 },
  { text: 'vente de cochon', action: 'create_revenu', params: {}, confidence: 0.9 },
  { text: 'vente de tete', action: 'create_revenu', params: {}, confidence: 0.9 },
  { text: 'vente de bete', action: 'create_revenu', params: {}, confidence: 0.9 },

  // ========== DÉPENSES (create_depense) - 80 exemples ==========
  { text: 'j ai depense [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'depense de [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai achete [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'achat de [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai paye [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'paiement de [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai claque [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'j ai depense [MONTANT] pour [CATEGORIE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour [CATEGORIE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]' }, confidence: 0.99 },
  { text: 'j ai achete [CATEGORIE] a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]' }, confidence: 0.99 },
  { text: 'achat de [CATEGORIE] a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]' }, confidence: 0.99 },
  { text: 'j ai paye [MONTANT] pour [CATEGORIE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]' }, confidence: 0.99 },
  { text: 'paiement de [MONTANT] pour [CATEGORIE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] fcfa', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'depense de [MONTANT] francs', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai achete [MONTANT] f', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'achat de [MONTANT] f cfa', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.98 },
  { text: 'j ai depense [MONTANT] aujourd hui', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'depense de [MONTANT] aujourd hui', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'j ai achete [MONTANT] ce matin', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'achat de [MONTANT] ce matin', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'j ai paye [MONTANT] hier', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'paiement de [MONTANT] hier', action: 'create_depense', params: { montant: '[MONTANT]' }, confidence: 0.97 },
  { text: 'j ai depense [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'depense de [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'j ai achete [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'achat de [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'j ai paye [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'paiement de [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'j ai depense [MONTANT] pour [CATEGORIE] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour [CATEGORIE] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'j ai achete [CATEGORIE] a [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'achat de [CATEGORIE] a [MONTANT] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'j ai paye [MONTANT] pour [CATEGORIE] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'paiement de [MONTANT] pour [CATEGORIE] le [DATE]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: '[CATEGORIE]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'j ai achete de la provende a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.98 },
  { text: 'achat de provende a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.98 },
  { text: 'j ai achete de la nourriture a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.98 },
  { text: 'achat de nourriture a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.98 },
  { text: 'j ai achete de l aliment a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.98 },
  { text: 'achat d aliment a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.98 },
  { text: 'j ai achete des medicaments a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'achat de medicaments a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'j ai achete des medocs a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'achat de medocs a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'j ai paye le veto a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'paiement du veto a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'j ai paye le veterinaire a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'paiement du veterinaire a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.98 },
  { text: 'j ai depense [MONTANT] pour la provende', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour la provende', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] pour la nourriture', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour la nourriture', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] pour l aliment', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour l aliment', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] pour les medicaments', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour les medicaments', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] pour les medocs', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour les medocs', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] pour le veto', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour le veto', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'j ai depense [MONTANT] pour le veterinaire', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'depense de [MONTANT] pour le veterinaire', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'sante' }, confidence: 0.99 },
  { text: 'j ai achete [QUANTITE] sacs de provende a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'achat de [QUANTITE] sacs de provende a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'j ai achete [QUANTITE] sacs de nourriture a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'achat de [QUANTITE] sacs de nourriture a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'j ai achete [QUANTITE] sacs d aliment a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'achat de [QUANTITE] sacs d aliment a [MONTANT]', action: 'create_depense', params: { montant: '[MONTANT]', categorie: 'alimentation' }, confidence: 0.99 },
  { text: 'depense', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'depenses', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'j ai depense', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'j ai achete', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'j ai paye', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'j ai claque', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'achat', action: 'create_depense', params: {}, confidence: 0.85 },
  { text: 'paiement', action: 'create_depense', params: {}, confidence: 0.85 },

  // ========== PESÉES (create_pesee) - 60 exemples ==========
  { text: 'peser [CODE_ANIMAL] il fait [POIDS]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'pesee de [CODE_ANIMAL] il fait [POIDS]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] fait [POIDS]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.98 },
  { text: '[CODE_ANIMAL] pese [POIDS]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.98 },
  { text: 'il fait [POIDS]', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.95 },
  { text: 'il pese [POIDS]', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.95 },
  { text: 'elle fait [POIDS]', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.95 },
  { text: 'elle pese [POIDS]', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.95 },
  { text: 'peser [CODE_ANIMAL]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.9 },
  { text: 'pesee de [CODE_ANIMAL]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.9 },
  { text: 'peser [CODE_ANIMAL] a [POIDS]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'pesee de [CODE_ANIMAL] a [POIDS]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'peser [CODE_ANIMAL] [POIDS] kg', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'pesee de [CODE_ANIMAL] [POIDS] kg', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'peser [CODE_ANIMAL] [POIDS] kilogrammes', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'pesee de [CODE_ANIMAL] [POIDS] kilogrammes', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'peser [CODE_ANIMAL] [POIDS] kilos', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'pesee de [CODE_ANIMAL] [POIDS] kilos', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] fait [POIDS] kg', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] pese [POIDS] kg', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] fait [POIDS] kilogrammes', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] pese [POIDS] kilogrammes', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] fait [POIDS] kilos', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] pese [POIDS] kilos', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]' }, confidence: 0.99 },
  { text: 'il fait [POIDS] kg', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'il pese [POIDS] kg', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'elle fait [POIDS] kg', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'elle pese [POIDS] kg', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'il fait [POIDS] kilogrammes', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'il pese [POIDS] kilogrammes', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'elle fait [POIDS] kilogrammes', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'elle pese [POIDS] kilogrammes', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'il fait [POIDS] kilos', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'il pese [POIDS] kilos', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'elle fait [POIDS] kilos', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'elle pese [POIDS] kilos', action: 'create_pesee', params: { poids_kg: '[POIDS]' }, confidence: 0.96 },
  { text: 'peser [CODE_ANIMAL] le [DATE]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', date: '[DATE]' }, confidence: 0.95 },
  { text: 'pesee de [CODE_ANIMAL] le [DATE]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', date: '[DATE]' }, confidence: 0.95 },
  { text: 'peser [CODE_ANIMAL] il fait [POIDS] le [DATE]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]', date: '[DATE]' }, confidence: 0.99 },
  { text: 'pesee de [CODE_ANIMAL] il fait [POIDS] le [DATE]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]', date: '[DATE]' }, confidence: 0.99 },
  { text: '[CODE_ANIMAL] fait [POIDS] le [DATE]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]', date: '[DATE]' }, confidence: 0.98 },
  { text: '[CODE_ANIMAL] pese [POIDS] le [DATE]', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]', poids_kg: '[POIDS]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'peser [CODE_ANIMAL] aujourd hui', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.92 },
  { text: 'pesee de [CODE_ANIMAL] aujourd hui', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.92 },
  { text: 'peser [CODE_ANIMAL] ce matin', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.92 },
  { text: 'pesee de [CODE_ANIMAL] ce matin', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.92 },
  { text: 'peser [CODE_ANIMAL] hier', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.92 },
  { text: 'pesee de [CODE_ANIMAL] hier', action: 'create_pesee', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.92 },
  { text: 'peser', action: 'create_pesee', params: {}, confidence: 0.85 },
  { text: 'pesee', action: 'create_pesee', params: {}, confidence: 0.85 },
  { text: 'pese', action: 'create_pesee', params: {}, confidence: 0.85 },
  { text: 'il fait', action: 'create_pesee', params: {}, confidence: 0.8 },
  { text: 'il pese', action: 'create_pesee', params: {}, confidence: 0.8 },
  { text: 'elle fait', action: 'create_pesee', params: {}, confidence: 0.8 },
  { text: 'elle pese', action: 'create_pesee', params: {}, confidence: 0.8 },

  // ========== VACCINATIONS (create_vaccination) - 50 exemples ==========
  { text: 'j ai vaccine [CODE_ANIMAL]', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.97 },
  { text: 'vaccination de [CODE_ANIMAL]', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.97 },
  { text: 'j ai vaccine [CODE_ANIMAL] le [DATE]', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'vaccination de [CODE_ANIMAL] le [DATE]', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]', date: '[DATE]' }, confidence: 0.98 },
  { text: 'j ai vaccine [CODE_ANIMAL] aujourd hui', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.96 },
  { text: 'vaccination de [CODE_ANIMAL] aujourd hui', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.96 },
  { text: 'j ai vaccine [CODE_ANIMAL] ce matin', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.96 },
  { text: 'vaccination de [CODE_ANIMAL] ce matin', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.96 },
  { text: 'j ai vaccine [CODE_ANIMAL] hier', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.96 },
  { text: 'vaccination de [CODE_ANIMAL] hier', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.96 },
  { text: 'j ai vaccine [QUANTITE] porcs', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vaccination de [QUANTITE] porcs', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vaccine [QUANTITE] cochons', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vaccination de [QUANTITE] cochons', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vaccine [QUANTITE] tetes', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vaccination de [QUANTITE] tetes', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vaccine [QUANTITE] betes', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'vaccination de [QUANTITE] betes', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.95 },
  { text: 'j ai vaccine [QUANTITE] porcs le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'vaccination de [QUANTITE] porcs le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'j ai vaccine [QUANTITE] cochons le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'vaccination de [QUANTITE] cochons le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'j ai vaccine [QUANTITE] tetes le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'vaccination de [QUANTITE] tetes le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'j ai vaccine [QUANTITE] betes le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'vaccination de [QUANTITE] betes le [DATE]', action: 'create_vaccination', params: { nombre: '[QUANTITE]', date: '[DATE]' }, confidence: 0.96 },
  { text: 'vacciner [CODE_ANIMAL]', action: 'create_vaccination', params: { animal_code: '[CODE_ANIMAL]' }, confidence: 0.95 },
  { text: 'vacciner [QUANTITE] porcs', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.94 },
  { text: 'vacciner [QUANTITE] cochons', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.94 },
  { text: 'vacciner [QUANTITE] tetes', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.94 },
  { text: 'vacciner [QUANTITE] betes', action: 'create_vaccination', params: { nombre: '[QUANTITE]' }, confidence: 0.94 },
  { text: 'vaccin', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vaccination', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vacciner', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'j ai vaccine', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vaccine', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vaccines', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vaccination de', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vacciner de', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'j ai vaccine de', action: 'create_vaccination', params: {}, confidence: 0.85 },
  { text: 'vaccination de porc', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vaccination de cochon', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vaccination de tete', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vaccination de bete', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vacciner porc', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vacciner cochon', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vacciner tete', action: 'create_vaccination', params: {}, confidence: 0.9 },
  { text: 'vacciner bete', action: 'create_vaccination', params: {}, confidence: 0.9 },

  // ========== STOCKS (get_stock_status) - 40 exemples ==========
  { text: 'combien de provende j ai', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'stock de provende', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'combien de nourriture j ai', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'stock de nourriture', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'combien d aliment j ai', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'stock d aliment', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'mes stocks', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'mes stocks de provende', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'mes stocks de nourriture', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'mes stocks d aliment', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'etat de mes stocks', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'situation de mes stocks', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'bilan de mes stocks', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'resume de mes stocks', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'combien de provende il me reste', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'provende restante', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'combien de nourriture il me reste', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'nourriture restante', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'combien d aliment il me reste', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'aliment restant', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'provende', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'nourriture', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'aliment', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'aliments', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'stock', action: 'get_stock_status', params: {}, confidence: 0.85 },
  { text: 'stocks', action: 'get_stock_status', params: {}, confidence: 0.85 },
  { text: 'combien de provende', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'combien de nourriture', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'combien d aliment', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'il me reste combien de provende', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'il me reste combien de nourriture', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'il me reste combien d aliment', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'reste combien de provende', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'reste combien de nourriture', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'reste combien d aliment', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'quantite de provende', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'quantite de nourriture', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'quantite d aliment', action: 'get_stock_status', params: {}, confidence: 0.9 },
  { text: 'nombre de sacs de provende', action: 'get_stock_status', params: {}, confidence: 0.95 },
  { text: 'nombre de sacs de nourriture', action: 'get_stock_status', params: {}, confidence: 0.95 },

  // ========== COÛTS (calculate_costs) - 40 exemples ==========
  { text: 'combien j ai depense', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses totales', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'total de mes depenses', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'somme de mes depenses', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'montant total de mes depenses', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'combien j ai depense ce mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses ce mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses du mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'depenses du mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'combien j ai depense cette semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses cette semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses de la semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'depenses de la semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'combien j ai depense aujourd hui', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses aujourd hui', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'depenses aujourd hui', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'combien j ai depense hier', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes depenses hier', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'depenses hier', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts totaux', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'total de mes couts', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'somme de mes couts', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'montant total de mes couts', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts ce mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts du mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'couts du mois', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts cette semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts de la semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'couts de la semaine', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts aujourd hui', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'couts aujourd hui', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'mes couts hier', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'couts hier', action: 'calculate_costs', params: {}, confidence: 0.95 },
  { text: 'bilan financier', action: 'calculate_costs', params: {}, confidence: 0.9 },
  { text: 'bilan des depenses', action: 'calculate_costs', params: {}, confidence: 0.9 },
  { text: 'bilan des couts', action: 'calculate_costs', params: {}, confidence: 0.9 },
  { text: 'resume financier', action: 'calculate_costs', params: {}, confidence: 0.9 },
  { text: 'resume des depenses', action: 'calculate_costs', params: {}, confidence: 0.9 },
  { text: 'resume des couts', action: 'calculate_costs', params: {}, confidence: 0.9 },

  // ========== QUESTIONS CONNAISSANCES (answer_knowledge_question) - 60 exemples ==========
  { text: 'c est quoi un naisseur', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'c est quoi un naisseur' }, confidence: 0.96 },
  { text: 'qu est ce qu un naisseur', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'qu est ce qu un naisseur' }, confidence: 0.96 },
  { text: 'explique moi un naisseur', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'explique moi un naisseur' }, confidence: 0.96 },
  { text: 'c est quoi un engraisseur', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'c est quoi un engraisseur' }, confidence: 0.96 },
  { text: 'qu est ce qu un engraisseur', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'qu est ce qu un engraisseur' }, confidence: 0.96 },
  { text: 'explique moi un engraisseur', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'explique moi un engraisseur' }, confidence: 0.96 },
  { text: 'c est quoi un cycle complet', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'c est quoi un cycle complet' }, confidence: 0.96 },
  { text: 'qu est ce qu un cycle complet', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'qu est ce qu un cycle complet' }, confidence: 0.96 },
  { text: 'explique moi un cycle complet', action: 'answer_knowledge_question', params: { topic: 'types_elevage', question: 'explique moi un cycle complet' }, confidence: 0.96 },
  { text: 'quelle race choisir', action: 'answer_knowledge_question', params: { topic: 'races', question: 'quelle race choisir' }, confidence: 0.96 },
  { text: 'quelle race est meilleure', action: 'answer_knowledge_question', params: { topic: 'races', question: 'quelle race est meilleure' }, confidence: 0.96 },
  { text: 'meilleure race de porc', action: 'answer_knowledge_question', params: { topic: 'races', question: 'meilleure race de porc' }, confidence: 0.96 },
  { text: 'comment nourrir mes porcs', action: 'answer_knowledge_question', params: { topic: 'alimentation', question: 'comment nourrir mes porcs' }, confidence: 0.96 },
  { text: 'comment formuler une ration', action: 'answer_knowledge_question', params: { topic: 'alimentation', question: 'comment formuler une ration' }, confidence: 0.96 },
  { text: 'comment fabriquer son aliment', action: 'answer_knowledge_question', params: { topic: 'alimentation', question: 'comment fabriquer son aliment' }, confidence: 0.96 },
  { text: 'combien coute l alimentation', action: 'answer_knowledge_question', params: { topic: 'alimentation', question: 'combien coute l alimentation' }, confidence: 0.96 },
  { text: 'cout de l alimentation', action: 'answer_knowledge_question', params: { topic: 'alimentation', question: 'cout de l alimentation' }, confidence: 0.96 },
  { text: 'comment vacciner mes porcs', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'comment vacciner mes porcs' }, confidence: 0.96 },
  { text: 'calendrier de vaccination', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'calendrier de vaccination' }, confidence: 0.96 },
  { text: 'programme vaccinal', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'programme vaccinal' }, confidence: 0.96 },
  { text: 'maladies des porcs', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'maladies des porcs' }, confidence: 0.96 },
  { text: 'prophylaxie porcine', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'prophylaxie porcine' }, confidence: 0.96 },
  { text: 'biosecurite', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'biosecurite' }, confidence: 0.96 },
  { text: 'duree de gestation', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'duree de gestation' }, confidence: 0.96 },
  { text: 'duree gestation truie', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'duree gestation truie' }, confidence: 0.96 },
  { text: 'quelle est la duree de gestation', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'quelle est la duree de gestation' }, confidence: 0.96 },
  { text: 'combien de jours gestation truie', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'combien de jours gestation truie' }, confidence: 0.96 },
  { text: 'gestation truie', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'gestation truie' }, confidence: 0.96 },
  { text: 'reproduction porcine', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'reproduction porcine' }, confidence: 0.96 },
  { text: 'insemination truie', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'insemination truie' }, confidence: 0.96 },
  { text: 'saillie truie', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'saillie truie' }, confidence: 0.96 },
  { text: 'mise bas truie', action: 'answer_knowledge_question', params: { topic: 'sante', question: 'mise bas truie' }, confidence: 0.96 },
  { text: 'comment calculer ma rentabilite', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'comment calculer ma rentabilite' }, confidence: 0.96 },
  { text: 'combien gagner avec l elevage', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'combien gagner avec l elevage' }, confidence: 0.96 },
  { text: 'marge par porc', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'marge par porc' }, confidence: 0.96 },
  { text: 'investissement initial', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'investissement initial' }, confidence: 0.96 },
  { text: 'seuil de rentabilite', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'seuil de rentabilite' }, confidence: 0.96 },
  { text: 'combien pour demarrer', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'combien pour demarrer' }, confidence: 0.96 },
  { text: 'capital necessaire', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'capital necessaire' }, confidence: 0.96 },
  { text: 'budget elevage', action: 'answer_knowledge_question', params: { topic: 'finance', question: 'budget elevage' }, confidence: 0.96 },
  { text: 'ou vendre mes porcs', action: 'answer_knowledge_question', params: { topic: 'commerce', question: 'ou vendre mes porcs' }, confidence: 0.96 },
  { text: 'comment vendre mes porcs', action: 'answer_knowledge_question', params: { topic: 'commerce', question: 'comment vendre mes porcs' }, confidence: 0.96 },
  { text: 'prix de vente', action: 'answer_knowledge_question', params: { topic: 'commerce', question: 'prix de vente' }, confidence: 0.96 },
  { text: 'canaux de commercialisation', action: 'answer_knowledge_question', params: { topic: 'commerce', question: 'canaux de commercialisation' }, confidence: 0.96 },
  { text: 'trouver des clients', action: 'answer_knowledge_question', params: { topic: 'commerce', question: 'trouver des clients' }, confidence: 0.96 },
  { text: 'demarrer un elevage', action: 'answer_knowledge_question', params: { topic: 'objectifs', question: 'demarrer un elevage' }, confidence: 0.96 },
  { text: 'par ou commencer', action: 'answer_knowledge_question', params: { topic: 'objectifs', question: 'par ou commencer' }, confidence: 0.96 },
  { text: 'definir son objectif', action: 'answer_knowledge_question', params: { topic: 'objectifs', question: 'definir son objectif' }, confidence: 0.96 },
  { text: 'ou construire ma porcherie', action: 'answer_knowledge_question', params: { topic: 'emplacement', question: 'ou construire ma porcherie' }, confidence: 0.96 },
  { text: 'emplacement porcherie', action: 'answer_knowledge_question', params: { topic: 'emplacement', question: 'emplacement porcherie' }, confidence: 0.96 },
  { text: 'terrain pour elevage', action: 'answer_knowledge_question', params: { topic: 'emplacement', question: 'terrain pour elevage' }, confidence: 0.96 },
  { text: 'distance habitations', action: 'answer_knowledge_question', params: { topic: 'emplacement', question: 'distance habitations' }, confidence: 0.96 },
  { text: 'besoin en eau', action: 'answer_knowledge_question', params: { topic: 'eau', question: 'besoin en eau' }, confidence: 0.96 },
  { text: 'combien d eau', action: 'answer_knowledge_question', params: { topic: 'eau', question: 'combien d eau' }, confidence: 0.96 },
  { text: 'qualite de l eau', action: 'answer_knowledge_question', params: { topic: 'eau', question: 'qualite de l eau' }, confidence: 0.96 },
  { text: 'forage ou puits', action: 'answer_knowledge_question', params: { topic: 'eau', question: 'forage ou puits' }, confidence: 0.96 },
  { text: 'reglementation elevage', action: 'answer_knowledge_question', params: { topic: 'reglementation', question: 'reglementation elevage' }, confidence: 0.96 },
  { text: 'obligations legales', action: 'answer_knowledge_question', params: { topic: 'reglementation', question: 'obligations legales' }, confidence: 0.96 },
  { text: 'normes sanitaires', action: 'answer_knowledge_question', params: { topic: 'reglementation', question: 'normes sanitaires' }, confidence: 0.96 },
  { text: 'declaration d elevage', action: 'answer_knowledge_question', params: { topic: 'reglementation', question: 'declaration d elevage' }, confidence: 0.96 },
  { text: 'c est quoi', action: 'answer_knowledge_question', params: {}, confidence: 0.9 },
  { text: 'qu est ce que', action: 'answer_knowledge_question', params: {}, confidence: 0.9 },
  { text: 'explique moi', action: 'answer_knowledge_question', params: {}, confidence: 0.9 },
  { text: 'comment', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
  { text: 'pourquoi', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
  { text: 'difference entre', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
  { text: 'conseils', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
  { text: 'recommandations', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
  { text: 'avantages', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
  { text: 'inconvenients', action: 'answer_knowledge_question', params: {}, confidence: 0.85 },
];

