/**
 * Configuration de la navigation
 */

export const SCREENS = {
  WELCOME: 'Welcome',
  AUTH: 'Auth',
  CREATE_PROJECT: 'CreateProject',
  DASHBOARD: 'Dashboard',
  DASHBOARD_BUYER: 'DashboardBuyer',
  DASHBOARD_VET: 'DashboardVet',
  DASHBOARD_TECH: 'DashboardTech',
  PROFIL: 'Profil',
  REPRODUCTION: 'Reproduction',
  NUTRITION: 'Nutrition',
  PRODUCTION: 'Production',
  SANTE: 'Sante',
  FINANCE: 'Finance',
  REPORTS: 'Reports',
  PLANIFICATION: 'Planification',
  PARAMETRES: 'Parametres',
  TRAINING: 'Training',
  COLLABORATION: 'Collaboration',
  MORTALITES: 'Mortalites',
  ADMIN: 'Admin',
  MARKETPLACE: 'Marketplace',
  MARKETPLACE_CHAT: 'MarketplaceChat',
  DOCUMENTS: 'Documents',
  // 🆕 Écrans spécifiques aux rôles
  MY_PURCHASES: 'MyPurchases',
  MY_CLIENTS: 'MyClients',
  CONSULTATIONS: 'Consultations',
  MY_FARMS: 'MyFarms',
  TASKS: 'Tasks',
  RECORDS: 'Records',
  OFFERS: 'Offers',
  // 🆕 Écrans d'onboarding
  ONBOARDING_AUTH: 'OnboardingAuth',
  PROFILE_SELECTION: 'ProfileSelection',
  BUYER_INFO_COMPLETION: 'BuyerInfoCompletion',
  VETERINARIAN_INFO_COMPLETION: 'VeterinarianInfoCompletion',
  VET_PROPOSE_FARMS: 'VetProposeFarms',
  SERVICE_PROPOSAL_NOTIFICATIONS: 'ServiceProposalNotifications',
  // Agent conversationnel
  CHAT_AGENT: 'ChatAgent',
  // 🆕 Écrans additionnels
  MY_PROJECTS: 'MyProjects',
  STATISTICS: 'Statistics',
  COLLABORATION_VET_TECH: 'CollaborationVetTech',
  MANAGE_PROFILES: 'ManageProfiles',
  MY_QR_CODE: 'MyQRCode',
  SCAN_QR_COLLABORATEUR: 'ScanQRCollaborateur',
  QR_INVITATION_CONFIG: 'QRInvitationConfig',
  LOGIN_LOGS: 'LoginLogs',
  SIGN_UP_METHOD: 'SignUpMethod',
  PHONE_SIGN_UP: 'PhoneSignUp',
  RESET_PASSWORD: 'ResetPassword',
  OTP_VERIFICATION: 'OtpVerification',
  USER_INFO: 'UserInfo',
  WEIGHING: 'Weighing',
  PLANNING_PRODUCTION: 'PlanningProduction',
  TRANSACTION_DETAIL: 'TransactionDetail',
  DISEASE: 'Disease',
  GESTATION: 'Gestation',
  MORTALITY: 'Mortality',
  SALE: 'Sale',
  SIGN_IN: 'SignIn',
  SUJET_PESEE_DETAIL: 'SujetPeseeDetail',
  VACCINATION: 'Vaccination',
  VET_CONSULTATIONS: 'VetConsultations',
  VET_PROJECT_DETAIL: 'VetProjectDetail',
  VET_REPORTS: 'VetReports',
  VET_TREATMENTS: 'VetTreatments',
  FORGOT_PASSWORD: 'ForgotPassword',
} as const;

export type ScreenName = (typeof SCREENS)[keyof typeof SCREENS];
